### ISSUE TITLE
About Noise-aware Iterative Labeling

### ISSUE THREAD

**Issue by lyb92nlf** [shaofeifei11/SSDR-AL#2]
@shaofeifei11, I have two questions:

1. Whether the purity calculation is based on the prediction result of the segmentation module?
2. In your paper, you describe "split v into a sub-region set R according to the pseudo prediction class of points". In this case, shouldn't the purity of each sub region be 100%？

Look forward to your reply！

**Comment by shaofeifei11** [comment]
Hello！

1. "we first define the purity ϕ(v) of a superpoint v as the percentage of majority points within the superpoint v".  The purity calculation is based on the ground-truth pixel label. It is evaluated by Oracle.
2. Yes. "we empower the oracle to consume “one click” to split v into a sub-region set R according to the pseudo prediction class of points". The purity of each sub-region is not necessarily 100%, we have done some comparative experiments with different purities in Figure 5 (b)

**Comment by lyb92nlf** [comment]
Got it, thanks.
